### ISSUE TITLE
Site broken on Firefox

### ISSUE THREAD

**Issue by tilda** [memework/generic-sucks#12]
Version: Firefox ESR v45.7.0, running on RPi3 - ARMv7, Raspbian Stretch/testing

Issue: "GENERIC SUCKS" is way off and the plane is too zoomed in - you can see this in the screenshot
![screenshot from 2017-04-02 17-42-05](https://cloud.githubusercontent.com/assets/8301262/24591633/14523812-17cc-11e7-843b-4a135c0ca636.png)

**Comment by slice** [comment]
Upgrade to the latest version of Firefox, the site uses new CSS/HTML5 features that are not supported on older browsers.

**Comment by tilda** [comment]
Explains then - but I'm on testing which does old browser shit really. Will probably upgrade if I find a way (without building it and possibly making my Pi explode lol)
